import { AppRegistry } from 'react-native'
import Basic from './components/Basic/'
// import Dynamic from './components/Dynamic/'
// import Phone from './components/Phone/'
// import Swiper from './components/Swiper/'
// import SwiperNumber from './components/SwiperNumber/'
// import LoadMinimal from './components/LoadMinimal/'
// import PhotoView from './components/PhotoView/'
// import Header from './components/Header/'
AppRegistry.registerComponent('examples', () => Basic)
